version: '3.7'
services:
  mysql:
    image: mysql:8
    container_name: buecher-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: buechersammlung
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306" # Ändere nicht auf 3307, da auf dem Server 3306 frei sein sollte
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./buecher-backend
    container_name: buecher-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: buechersammlung
      DB_PORT: 3306 # MySQL wird im Container auf 3306 laufen

  frontend:
    build: ./buecher-frontend
    container_name: buecher-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
